/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package activos_intangibles.Interfaz.gestion_license;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author serbi
 */
public class delete_license extends javax.swing.JFrame {

    private javax.swing.JButton btnEliminar;
private javax.swing.JScrollPane jScrollPane1;
private javax.swing.JTable jtVista;
    
    /**
     * Creates new form delete_license
     */
    public delete_license() {
          initComponents();
    cargarDatosEnTabla();
    // Agregar listener al botón eliminar
    btnEliminar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            eliminarLicenciaSeleccionada();
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtVista = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtVista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tipo de Licencia", "Costo", "Fecha Compra", "Fecha Fin", "Vida Util", "Valor en Libros", "Valor Pendiente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtVista);

        btnEliminar.setText("Elliminar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEliminar)
                .addGap(335, 335, 335))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(delete_license.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(delete_license.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(delete_license.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(delete_license.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new delete_license().setVisible(true);
        }
    }); 
} 
    
                 
    private void cargarDatosEnTabla() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("id");  // Asegúrate de incluir la columna clave
        modelo.addColumn("Tipo Licencia");
        modelo.addColumn("Costo");
        modelo.addColumn("Fecha Compra");
        modelo.addColumn("Fecha Fin");
        modelo.addColumn("Vida Util");
        modelo.addColumn("Valor en Libros");
        modelo.addColumn("Valor pendiente");

        try {
            Connection con = DriverManager.getConnection(
                "jdbc:postgresql://localhost:5433/Activos_Intangibles",
                "postgres",
                "255623"
            );
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT idlicencia,tipolicencia, costo, fechacompra, fechafin, vidautil, valorenlibros, valorpendientes FROM licencia");

            while (rs.next()) {
                modelo.addRow(new Object[] {
                     rs.getString("idlicencia"),
                    rs.getString("tipolicencia"),
                    rs.getDouble("costo"),
                    rs.getDate("fechacompra"),
                    rs.getDate("fechafin"),
                    rs.getInt("vidautil"),
                    rs.getDouble("valorenlibros"),
                    rs.getDouble("valorpendientes")
                });
            }

            jtVista.setModel(modelo);

            st.close();
            con.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar datos: " + e.getMessage());
        }
    }

    private void eliminarLicenciaSeleccionada() {
       
    int filaSeleccionada = jtVista.getSelectedRow();
    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona una licencia para eliminar.");
        return;
    }

    try {
        
        String idStr = jtVista.getValueAt(filaSeleccionada, 0).toString();
        int idLicencia = Integer.parseInt(idStr);

        int confirmacion = JOptionPane.showConfirmDialog(this,
            "¿Estás seguro que quieres eliminar la licencia con ID " + idLicencia + "?",
            "Confirmar eliminación",
            JOptionPane.YES_NO_OPTION);

        if (confirmacion != JOptionPane.YES_OPTION) {
            return;
        }

        Connection con = DriverManager.getConnection(
            "jdbc:postgresql://localhost:5433/Activos_Intangibles",
            "postgres",
            "255623"
        );

        String sql = "DELETE FROM licencia WHERE idlicencia = ?";
        PreparedStatement ps = con.prepareStatement(sql);
        ps.setInt(1, idLicencia);

        int resultado = ps.executeUpdate();

        if (resultado > 0) {
            JOptionPane.showMessageDialog(this, "Licencia eliminada correctamente.");
            cargarDatosEnTabla();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo eliminar la licencia.");
        }

        ps.close();
        con.close();

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "ID inválido: " + e.getMessage());
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al eliminar licencia: " + e.getMessage());
    }
}
    
}
/*
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtVista;
    // End of variables declaration//GEN-END:variables
}*/
