/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package activos_intangibles.Interfaz.gestion_license;

import activos_intangibles.Interfaz.gestion_license.create_license;
import activos_intangibles.Interfaz.gestion_license.delete_license;
import activos_intangibles.Interfaz.gestion_license.update_license;
import activos_intangibles.Interfaz.gestion_license.view_table_gestion;
import activos_intangibles.Interfaz.main_menu_screen;


import javax.swing.JOptionPane;

/**
 *
 * @author serbi
 */
public class menu_gestion_license extends javax.swing.JFrame {

    /**
     * Creates new form menu_gestion_licencia
     */
    public menu_gestion_license() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbCRUD = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jbtnEntrar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GESTION LICENSE\n");

        jcbCRUD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ver Licencias", "Crear Licencia", "Eliminar Licencia", "Actualizar Licencia" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Gestion Licencias");

        jbtnEntrar.setText("Entrar");
        jbtnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEntrarActionPerformed(evt);
            }
        });

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnEntrar)
                        .addGap(18, 18, 18)
                        .addComponent(btnAtras))
                    .addComponent(jLabel1)
                    .addComponent(jcbCRUD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jcbCRUD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnEntrar)
                    .addComponent(btnAtras))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEntrarActionPerformed

        String opcionCRUD = (String) jcbCRUD.getSelectedItem();

    switch (opcionCRUD) {
        case "Crear Licencia":
            create_license crear = new create_license();
            crear.setVisible(true);
            this.dispose();
            break;

        case "Ver Licencias":
            view_table_gestion ver = new view_table_gestion();
            ver.setVisible(true);
            this.dispose();
            break;

        case "Actualizar Licencia":
            update_license actualizar = new update_license();
            actualizar.setVisible(true);
            this.dispose();
            break;

        case "Eliminar Licencia":
            delete_license eliminar = new delete_license();
            eliminar.setVisible(true);
            this.dispose();
            break;

        default:
            JOptionPane.showMessageDialog(this, "Seleccione una opción válida.");
            break;
    }
     
 
        
    }//GEN-LAST:event_jbtnEntrarActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // Abrir la pantalla principal
    main_menu_screen menu = new main_menu_screen();
    menu.setVisible(true);
    menu.setLocationRelativeTo(null); // Centrar

    // Cerrar la actual
    dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_gestion_license.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_gestion_license.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_gestion_license.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_gestion_license.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_gestion_license().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtnEntrar;
    private javax.swing.JComboBox<String> jcbCRUD;
    // End of variables declaration//GEN-END:variables
}
